### PR TITLE
Make function names less generic

### PR DESCRIPTION
**Pull request by arippberger**
Some function names are too generic and run the risk of a collision. This PR appends many functions with 'tealium' to help prevent this problem.

### CODE REVIEW

**Comment by ianhampton** [comment]
Good idea, thank you!

**Comment by arippberger** [comment]
@ianhampton awesome - thanks for merging. Could you let me know when you update the plugin in the WP repo?

**Comment by ianhampton** [comment]
@arippberger released as version 2.1.5 through the repo just now. With credit to you in the changelog.

**Comment by arippberger** [comment]
@ianhampton thanks!

**Pull request merged**
